### ISSUE TITLE
Download link is a broken

### ISSUE THREAD

**Issue by serkandyck** [wenmingvs/AndroidProcess#1]

**Comment by wenmingvs** [comment]
I have tested  the download link and it works fine! Are you sure?  Try to use this 

http://nj02.poms.baidupcs.com/file/a6cc8737848bac3f88d9b62071fed159?bkt=p3-1400a6cc8737848bac3f88d9b62071fed1597ff4e9400000001b19d2&fid=705674832-250528-270497132391664&time=1453802302&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-1Mrk4%2F3hjRvX%2FXYukMFDP50Oees%3D&to=n2b&fm=Nan,B,T,t&sta_dx=2&sta_cs=0&sta_ft=apk&sta_ct=1&fm2=Nanjing02,B,T,t&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400a6cc8737848bac3f88d9b62071fed1597ff4e9400000001b19d2&sl=67436622&expires=8h&rt=sh&r=295882726&mlogid=597189103410289569&vuk=-&vbdid=2204890248&fin=sample-debug.apk&fn=sample-debug.apk&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=597189103410289569&dp-callid=0.1.1

**Comment by wenmingvs** [comment]
Sorry.Please download again. I have updated the link
