### ISSUE TITLE
注明最后一种判断方法引用的出处

### ISSUE THREAD

**Issue by tiann** [wenmingvs/AndroidProcess#3]
https://github.com/jaredrummler/AndroidProcesses

**Comment by jiongxuan** [comment]
还真是。实在有些浮躁。

我想楼主的Issue的诉求是：将首页“黑科技”的来源写清，保留作者的包名和版权信息。

另外，戒骄戒躁，才有机会成长更多。

**Comment by wenmingvs** [comment]
不好意思，我初来乍到并不懂，后面一定会加强版权意识。我之前看国内Android大神的下拉刷新Demo，https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh 他的Demo也引用了其他开源项目的下拉刷新Demo代码，并且做了一个汇总，也没有注明任何的来源。所以我也没有太重视这点了

另外，我并没有任何的抄袭他人代码出名的意思，只是做一个判断后台方法的汇总，以上5种方法网上均能找到出处，但是代码相当的零散，所以才做了一个Demo方便后面的开发者们更快理解和使用，并没有任何的出名之说

我已经在README做了相应的更改，并且备注好项目地址了，标注清楚并不是我原创，按照你的要求保留了作者的包名和版权信息

以上

**Comment by tiann** [comment]
项目整合的挺好用的，good～

**Comment by jiongxuan** [comment]
不错。谢谢采纳。

希望以后能做出更给力的作品！:)
