### ISSUE TITLE
通过registerActivityLifecycleCallbacks 判断是不准的

### ISSUE THREAD

**Issue by emile2013** [wenmingvs/AndroidProcess#7]
appCount甚至会出现负数

**Comment by wenmingvs** [comment]
你好，我还没有碰到你说这的这种情况。能否简单的还原一下情景？或者打印一下logcat给我看看？

**Comment by emile2013** [comment]
恩，你可以通过多个activity 的app进行测试，并多次退出进入后台。我先前有个统计项目，也是和你一个思路，后期数据发现appCount不一致情形。

**Comment by wenmingvs** [comment]
你对于appCount的计算位置跟我一样吗？会不会是在错误的生命周期方法中做了计算

**Comment by emile2013** [comment]
sorry，我看了下代码，我先前是用于统计页面路径的，和你的用法不一样。
